services:
  myservice:
    build: .
    container_name: myservice
    ports:
      - "8698:8000"
    environment:
      TRELLIX_API_URL: ${TRELLIX_API_URL:-}
      TRELLIX_API_TOKEN: ${TRELLIX_API_TOKEN:-}
      GPU_NAME: "NVIDIA GeForce RTX 5070 Ti"
    restart: unless-stopped
    volumes:
      - triposr-cache:/root/.cache/huggingface
    # GPU доступен контейнеру после установки nvidia-container-toolkit на сервере.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]

volumes:
  triposr-cache:
